version: '3.8'
services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - mysqldb_data:/var/lib/mysql+
      - ./db_init/init.db.sql:/docker-entrypoint-initdb.d/init.db.sql 

  app:
    build: .
    depends_on:
      - mysqldb
    environment:
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MYSQLDB_PORT=$MYSQLDB_PORT
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    volumes:
      - .:/myapp  # Esto montará tu código fuente en el contenedor
    command: npm run dev  # Cambia el comando para usar nodemon

  # Esta es la parte del frontend
  client:
    build:
      context: ./public/$WEB_NAME   # Cambiar aquí para apuntar a la nueva ubicación de la web
    ports:
      - $WEB_LOCAL_PORT:$WEB_DOCKER_PORT
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]

volumes:
  mysqldb_data:
