BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Gases" (
	"Nombre"	TEXT NOT NULL UNIQUE,
	"Medida min"	INTEGER NOT NULL,
	"Medida max"	INTEGER NOT NULL,
	"Info"	TEXT,
	PRIMARY KEY("Nombre")
);
CREATE TABLE IF NOT EXISTS "Medidas" (
	"ID"	INTEGER NOT NULL,
	"Gas"	TEXT,
	"Lugar"	TEXT,
	"Hora"	NUMERIC,
	"Valor"	INTEGER,
	"Sensor"	INTEGER,
	PRIMARY KEY("ID"),
	FOREIGN KEY("Gas") REFERENCES "Gases"("Nombre"),
	FOREIGN KEY("Sensor") REFERENCES "Sensor"("ID")
);
CREATE TABLE IF NOT EXISTS "Sensor" (
	"ID"	INTEGER NOT NULL,
	"Usuario"	INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("Usuario") REFERENCES "Usuarios"("ID")
);
CREATE TABLE IF NOT EXISTS "Usuarios" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Nombre"	TEXT,
	"Contraseña"	TEXT,
	"Correo"	TEXT,
	PRIMARY KEY("ID")
);
COMMIT;
